github: bgarciamoura
buy_me_a_coffee: bgarciamoura
custom: ["https://www.paypal.com/donate/?business=JLSTWHFM8KD3G&no_recurring=0&item_name=Built+with+love%2C+powered+by+coffee.+Your+support+keeps+Notion+Bases+free+and+growing+for+everyone.+Thank+you%21&currency_code=BRL"]
